# Generated by Django 4.2 on 2023-04-29 16:40

import datetime
from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('bnb_kingdom_api', '0005_alter_buyhistory_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=1024)),
                ('wallet_address_introduced', models.CharField(max_length=1024)),
                ('F_ratings', models.CharField(default='F?', max_length=54)),
                ('created_at', models.FloatField(default=time.time)),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'introduction',
            },
        ),
        migrations.CreateModel(
            name='PayInterest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=1024)),
                ('interest_introduced', models.FloatField(default=0)),
                ('interest_package', models.FloatField(default=0)),
                ('timeProccess', models.FloatField(default=0)),
                ('created_at', models.FloatField(default=time.time)),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.AddField(
            model_name='buyhistory',
            name='package_selected',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='buyhistory',
            table='buyhistory',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_123',
        ),
    ]
