# Generated by Django 4.2 on 2023-04-29 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bnb_kingdom_api', '0006_introduction_payinterest_buyhistory_package_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyhistory',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
